# The URL the site will be built for
base_url = "https://"
# The title of your page
title = ""
# A description (for those meta tags and such)
description = "LINMOB.net is a blog about LINux on MOBile devices. With the PinePhone and Librem 5 shipping it is back to report on GNU+Linux on mobile devices."
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme 
theme = "minimola"

# The language you're using
default_language = "en"
# custom feed.xml file for transitions from Jekyll in extras
feed_filename = "feed.xml" 
feed_limit = 10

# Yes, you want a ATOM feed!
generate_feed = true

# Taxonomies that this theme allows for
taxonomies = [
       {name = "tags", feed = true},
       {name = "categories", feed = true}, 
      ]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = true

[extra]
# Put all your custom variables here 
# Too many titles. Do I even use all of these
seo_title = "LINMOB.net | Librem 5, PinePhone, postmarketOS and more!" 
minima_title = "Custom Theme Title"
page_subtitle = "Subtitle" 
# Loads "/static/icon.png"
icon = true
# Name
author = ""
# Your full name
author_legalname = ""
# E-Mail for footer, beware of spam
email = ""
# Yet another description
description = "LINMOB.net is a blog about LINux on MOBile devices. With the PinePhone and Librem 5 shipping it is back to report on GNU+Linux on mobile devices."
# License, see also copyright below 
license = "Unless otherwise specified, all content on this page is licensed under CC-BY-SA 4.0."
# Optional menu in footer to link even more stuff
footer_menu =[ 
   {url = "$BASE_URL/legal-notice-gdpr/", name = "Legal Notice and GDPR conformity"},
]
# Show "Proudly powered by"
footer_credit = true

# Main navigation
blog_menu =[ 
   {url = "$BASE_URL/about", name = "About"},
   {url = "$BASE_URL/tags/", name = "Archive"},
]
# 404
not_found_message = "Sorry. This seems to be gone. :( Back to [safety](/)?"

# Social links for the footer. The ones without _username are the URL
[extra.social.links]
twitter_username = ""
twitter = ""
mastodon_username = ""
mastodon = ""
github_username = ""
github = ""
youtube_username = ""
youtube = ""
peertube_username = ""
peertube = ""
odysee_username = ""
odysee = ""
app_list_name = ""
app_list = ""
podcast_name = ""
podcast = ""
email_username = ""
email = ""
rss = "ATOM feed"

[extra.copyright]
owner = "Your name"
time = "2007-2021"
# License, if you use one and URL
license = "CC-BY-SA 4.0"
license_link = "https://creativecommons.org/licenses/by-sa/4.0/"

