name = "minimola"
description = " Minima v2 adapted for Zola "
license = "MIT"
homepage = "https://github.com/1peter10/minimola"
min_version = "0.16.0"
demo = "https://linmob.net"

[extra]
blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
minima_title = "Minimola"

[author]
name = "Peter Mack"
homepage = "https://linmob.net/authors/peter"

[original]
author =  "minima contributors"
homepage = "https://jekyll.github.io/minima"
repo = "https://github.com/jekyll/minima"
